{
  throw new RuntimeException("(Expected) exception thrown by test");
}
